
export const FETCH_ROLE='FETCH_ROLE'
export const LOGIN='LOGIN'
export const SIGN_UP='SIGN_UP'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const PROMPT_TO_SIGN='PROMPT_TO_SIGN'
export const SHOW_NOTIFICATION='SHOW_NOTIFICATION'